spring:
    datasource:
        url: jdbc:postgres://localhost.5432/postgres
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                package-to-scan: br.com.monstro.fakeapied.infrastructure.entites
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    cloud:
        loadbalancer:
            ribbon:
                enable: true

fake-api:
    url: https://fakestoreapi.com

server:
    port: 8181